package downloader

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/gotd/td/tg"
)

type MediaKind string

const (
	KindPhoto   MediaKind = "photo"
	KindVideo   MediaKind = "video"
	KindSong    MediaKind = "song"
	KindSticker MediaKind = "sticker"
	KindFile    MediaKind = "file"
)

type MediaInfo struct {
	Location         tg.InputFileLocationClass
	FileName         string
	CaptionFileName  string // Nombre basado en caption
	OriginalFileName string // Nombre original del archivo
	Kind             MediaKind
	FileSize         int64
}

// invalidPathChars son los caracteres que ningún sistema admite en un nombre de
// archivo. Se incluyen «&», «^» y «%» aunque en Linux y macOS sean legales:
// esos tres los interpreta cmd.exe de Windows, y el nombre lo elige quien sube
// el archivo a Telegram, no quien lo descarga.
var invalidPathChars = regexp.MustCompile(`[<>:"/\\|?*&^%\x00-\x1f]`)

// reservedWindowsNames no se pueden usar como nombre de archivo en Windows ni
// con extensión detrás: «NUL.mp4» sigue siendo el dispositivo nulo.
var reservedWindowsNames = map[string]bool{
	"CON": true, "PRN": true, "AUX": true, "NUL": true,
	"COM1": true, "COM2": true, "COM3": true, "COM4": true, "COM5": true,
	"COM6": true, "COM7": true, "COM8": true, "COM9": true,
	"LPT1": true, "LPT2": true, "LPT3": true, "LPT4": true, "LPT5": true,
	"LPT6": true, "LPT7": true, "LPT8": true, "LPT9": true,
}

// maxFileNameBytes deja margen de sobra bajo el límite de 255 bytes que imponen
// NTFS, APFS y ext4, contando que después se le añade una ruta por delante.
const maxFileNameBytes = 200

// SanitizeFileName convierte el nombre que venga de Telegram en uno que se pueda
// escribir en disco sin sorpresas. El nombre es entrada no confiable: lo elige
// quien sube el archivo.
func SanitizeFileName(name string) string {
	clean := invalidPathChars.ReplaceAllString(name, "_")
	clean = strings.TrimSpace(clean)
	// Windows no admite que un nombre termine en punto o espacio.
	clean = strings.Trim(clean, ". ")
	if clean == "" {
		return "archivo"
	}

	clean = truncateFileName(clean)

	// El truncado puede dejar otra vez un punto o un espacio al final.
	clean = strings.Trim(clean, ". ")
	if clean == "" {
		return "archivo"
	}

	if isReservedWindowsName(clean) {
		clean = "_" + clean
	}

	return clean
}

// truncateFileName recorta el nombre conservando la extensión.
//
// La versión anterior hacía clean[:200-len(ext)], que con una extensión de más
// de 200 caracteres daba un índice negativo y reventaba el proceso entero: un
// nombre como «x.» seguido de 250 letras bastaba para tumbar la aplicación
// desde un mensaje de Telegram. Aquí la extensión se descarta si no cabe, y el
// corte es por runas para no partir un carácter UTF-8 por la mitad.
func truncateFileName(name string) string {
	if len(name) <= maxFileNameBytes {
		return name
	}

	ext := filepath.Ext(name)
	// Una «extensión» que ocupa casi todo el nombre no es una extensión.
	if len(ext) > maxFileNameBytes/2 {
		ext = ""
	}

	stem := strings.TrimSuffix(name, ext)
	stem = truncateRunes(stem, maxFileNameBytes-len(ext))

	result := stem + ext
	if result == "" || result == ext {
		return truncateRunes(name, maxFileNameBytes)
	}
	return result
}

// truncateRunes corta a lo sumo limit bytes sin partir ningún carácter.
func truncateRunes(s string, limit int) string {
	if limit <= 0 {
		return ""
	}
	if len(s) <= limit {
		return s
	}

	total := 0
	for i, r := range s {
		size := len(string(r))
		if total+size > limit {
			return s[:i]
		}
		total += size
	}
	return s
}

func isReservedWindowsName(name string) bool {
	base := name
	if i := strings.IndexByte(base, '.'); i >= 0 {
		base = base[:i]
	}
	return reservedWindowsNames[strings.ToUpper(strings.TrimSpace(base))]
}

// isAutoGeneratedName detecta si un nombre parece ser auto-generado por Telegram
// u otros sistemas basándose en patrones comunes.
func isAutoGeneratedName(name string) bool {
	// Quitamos la extensión para analizar solo el nombre base
	base := strings.TrimSuffix(name, filepath.Ext(name))

	// Patrón 1: Nombres con secuencias numéricas largas (ej: indexv1a1_0, IMG_3929)
	// Detecta 4 o más dígitos consecutivos
	if regexp.MustCompile(`\d{4,}`).MatchString(base) {
		return true
	}

	// Patrón 2: Nombres con combinación de letras técnicas y números
	// (ej: indexv1a1_0, photo_142454, video_2023)
	if regexp.MustCompile(`[a-z]*[0-9]+[a-z]*[0-9]+`).MatchString(base) {
		return true
	}

	// Patrón 3: Nombres que parecen identificadores técnicos
	// (ej: 142454, 3929, 123456789)
	if regexp.MustCompile(`^[0-9]{6,}$`).MatchString(base) {
		return true
	}

	// Patrón 4: Nombres con formato de timestamp o ID largo
	// (ej: 1704067200, 1234567890123)
	if regexp.MustCompile(`^[0-9]{10,}$`).MatchString(base) {
		return true
	}

	return false
}

func ExtractMediaInfo(msg *tg.Message) *MediaInfo {
	if msg == nil || msg.Media == nil {
		return nil
	}

	caption := msg.Message
	firstCaptionLine := ""
	if caption != "" {
		primeraLinea, _, _ := strings.Cut(caption, "\n")
		// El recorte va por runas, no por bytes. Cortando a 50 bytes, un texto
		// con acentos o con un emoji justo en el límite se partía por la mitad y
		// el nombre del archivo acababa con UTF-8 inválido.
		firstCaptionLine = strings.TrimSpace(truncateRunes(strings.TrimSpace(primeraLinea), 50))
	}

	switch m := msg.Media.(type) {
	case *tg.MessageMediaDocument:
		if doc, ok := m.Document.(*tg.Document); ok && doc != nil {
			return extractDocumentInfo(msg, doc, firstCaptionLine)
		}
	case *tg.MessageMediaPhoto:
		if photo, ok := m.Photo.(*tg.Photo); ok && photo != nil {
			return extractPhotoInfo(msg, photo, firstCaptionLine)
		}
	case *tg.MessageMediaWebPage:
		if wp, ok := m.Webpage.(*tg.WebPage); ok {
			if doc, ok := wp.Document.(*tg.Document); ok && doc != nil {
				return extractDocumentInfo(msg, doc, firstCaptionLine)
			}
			if photo, ok := wp.Photo.(*tg.Photo); ok && photo != nil {
				return extractPhotoInfo(msg, photo, firstCaptionLine)
			}
		}
	}

	return nil
}

func extractDocumentInfo(msg *tg.Message, doc *tg.Document, firstCaptionLine string) *MediaInfo {
	kind := KindFile
	fileName := ""
	isVoice := false
	audioTitle := ""
	audioPerformer := ""

	for _, attr := range doc.Attributes {
		switch a := attr.(type) {
		case *tg.DocumentAttributeFilename:
			fileName = a.FileName
		case *tg.DocumentAttributeVideo:
			kind = KindVideo
			if a.RoundMessage && fileName == "" {
				fileName = fmt.Sprintf("videonote_%d.mp4", msg.ID)
			}
		case *tg.DocumentAttributeAudio:
			kind = KindSong
			isVoice = a.Voice
			audioTitle = strings.TrimSpace(a.Title)
			audioPerformer = strings.TrimSpace(a.Performer)
		case *tg.DocumentAttributeSticker:
			kind = KindSticker
		case *tg.DocumentAttributeAnimated:
			kind = KindVideo
		}
	}

	mime := strings.ToLower(doc.MimeType)
	if fileName == "" {
		switch kind {
		case KindVideo:
			fileName = fmt.Sprintf("video_%d.mp4", msg.ID)
		case KindSong:
			if isVoice {
				fileName = fmt.Sprintf("voice_%d.ogg", msg.ID)
			} else if audioPerformer != "" && audioTitle != "" {
				fileName = fmt.Sprintf("%s - %s.mp3", audioPerformer, audioTitle)
			} else if audioTitle != "" {
				fileName = fmt.Sprintf("%s.mp3", audioTitle)
			} else {
				fileName = fmt.Sprintf("audio_%d.mp3", msg.ID)
			}
		case KindSticker:
			switch mime {
			case "application/x-tgsticker":
				fileName = fmt.Sprintf("sticker_%d.tgs", msg.ID)
			case "video/webm":
				fileName = fmt.Sprintf("sticker_%d.webm", msg.ID)
			default:
				fileName = fmt.Sprintf("sticker_%d.webp", msg.ID)
			}
		default:
			extByMime := extensionFromMime(mime)
			if extByMime != "" {
				fileName = fmt.Sprintf("file_%d%s", msg.ID, extByMime)
			} else {
				fileName = fmt.Sprintf("file_%d", msg.ID)
			}
		}
	}

	ext := filepath.Ext(fileName)
	lowerName := strings.ToLower(fileName)

	// Guardar el nombre original calculado
	originalFileName := SanitizeFileName(fileName)

	// Calcular el nombre basado en caption si existe
	captionFileName := ""
	if firstCaptionLine != "" {
		captionFileName = SanitizeFileName(firstCaptionLine) + ext
	}

	// Opción 1: Ampliar lista de prefijos genéricos
	genericPrefixes := []string{
		"video_", "doc_", "music_", "audio_", "voice_", "sticker_", "file_", "videonote_",
		"img_", "photo_", "vid_", "index", "snapchat", "screen", "screenshot",
		"whatsapp", "telegram", "download", "output", "temp", "cache",
	}
	isGeneric := false
	for _, p := range genericPrefixes {
		if strings.HasPrefix(lowerName, p) {
			isGeneric = true
			break
		}
	}

	// Opción 2: Detectar nombres auto-generados por patrón
	isAutoGenerated := isAutoGeneratedName(lowerName)

	// Opción 3: Usar caption si existe y el nombre es genérico o auto-generado
	// Ahora esto solo define el nombre predeterminado, pero guardamos ambas opciones
	finalFileName := originalFileName
	if firstCaptionLine != "" && (isGeneric || isAutoGenerated) {
		finalFileName = captionFileName
	}

	lowerExt := strings.ToLower(ext)
	if kind == KindFile {
		if strings.HasPrefix(mime, "image/") || lowerExt == ".jpg" || lowerExt == ".jpeg" || lowerExt == ".png" || lowerExt == ".webp" || lowerExt == ".gif" || lowerExt == ".heic" {
			kind = KindPhoto
		} else if strings.HasPrefix(mime, "video/") || lowerExt == ".mp4" || lowerExt == ".mkv" || lowerExt == ".webm" || lowerExt == ".avi" || lowerExt == ".mov" || lowerExt == ".flv" || lowerExt == ".wmv" || lowerExt == ".ts" || lowerExt == ".m4v" {
			kind = KindVideo
		} else if strings.HasPrefix(mime, "audio/") || lowerExt == ".mp3" || lowerExt == ".m4a" || lowerExt == ".flac" || lowerExt == ".wav" || lowerExt == ".ogg" || lowerExt == ".opus" || lowerExt == ".aac" || lowerExt == ".wma" {
			kind = KindSong
		}
	}

	loc := doc.AsInputDocumentFileLocation("")
	return &MediaInfo{
		Location:         loc,
		FileName:         finalFileName,
		CaptionFileName:  captionFileName,
		OriginalFileName: originalFileName,
		Kind:             kind,
		FileSize:         doc.Size,
	}
}

func extractPhotoInfo(msg *tg.Message, photo *tg.Photo, firstCaptionLine string) *MediaInfo {
	originalFileName := fmt.Sprintf("photo_%d.jpg", msg.ID)
	captionFileName := ""
	if firstCaptionLine != "" {
		captionFileName = fmt.Sprintf("%s.jpg", SanitizeFileName(firstCaptionLine))
	}

	// Usar caption como predeterminado si existe
	finalFileName := originalFileName
	if captionFileName != "" {
		finalFileName = captionFileName
	}

	var largest tg.PhotoSizeClass
	var fileSize int64
	for _, size := range photo.Sizes {
		switch s := size.(type) {
		case *tg.PhotoSize:
			largest = s
			if int64(s.Size) > fileSize {
				fileSize = int64(s.Size)
			}
		case *tg.PhotoSizeProgressive:
			largest = s
			if len(s.Sizes) > 0 {
				last := int64(s.Sizes[len(s.Sizes)-1])
				if last > fileSize {
					fileSize = last
				}
			}
		}
	}

	var thumbType string
	if largest != nil {
		thumbType = largest.GetType()
	} else {
		thumbType = "y"
	}

	loc := &tg.InputPhotoFileLocation{
		ID:            photo.ID,
		AccessHash:    photo.AccessHash,
		FileReference: photo.FileReference,
		ThumbSize:     thumbType,
	}

	return &MediaInfo{
		Location:         loc,
		FileName:         finalFileName,
		CaptionFileName:  captionFileName,
		OriginalFileName: originalFileName,
		Kind:             KindPhoto,
		FileSize:         fileSize,
	}
}

func extensionFromMime(mime string) string {
	switch mime {
	case "application/pdf":
		return ".pdf"
	case "application/zip":
		return ".zip"
	case "application/x-rar-compressed", "application/vnd.rar", "application/x-rar":
		return ".rar"
	case "application/x-7z-compressed":
		return ".7z"
	case "application/x-tar":
		return ".tar"
	case "application/gzip", "application/x-gzip":
		return ".gz"
	case "application/vnd.android.package-archive":
		return ".apk"
	case "text/plain":
		return ".txt"
	case "application/json":
		return ".json"
	case "application/msword":
		return ".doc"
	case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
		return ".docx"
	case "application/vnd.ms-excel":
		return ".xls"
	case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
		return ".xlsx"
	case "application/x-bittorrent":
		return ".torrent"
	default:
		return ""
	}
}
