// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function Handler():Promise<http.Handler>;

export function SelectDirectory():Promise<string>;
