// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function Handler() {
  return window['go']['main']['App']['Handler']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
